#### Options: History

# This option works like APPEND_HISTORY except that new history lines are added
# to the $HISTFILE incrementally (as soon as they are entered), rather than
# waiting until the shell exits. The file will still be periodically re-written
# to trim it when the number of lines grows 20% beyond the value specified by
# $SAVEHIST (see also the HIST_SAVE_BY_COPY option).

setopt INC_APPEND_HISTORY

#### Options: Corrections

# n: execute as typed
# y: accept and execute the suggested correction
# a: abort and do nothing
# e: return to the prompt to continue editing

# Try to correct the spelling of commands. Note that, when the HASH_LIST_ALL
# option is not set or when some directories in the path are not readable, this
# may falsely report spelling errors the first time some commands are used.

# The shell variable CORRECT_IGNORE may be set to a pattern to match words that
# will never be offered as corrections.

setopt CORRECT

# Try to correct the spelling of all arguments in a line.

# The shell variable CORRECT_IGNORE_FILE may be set to a pattern to match file
# names that will never be offered as corrections.

setopt CORRECT_ALL

#### Completion System

autoload -Uz compinit && compinit

#### Aliases: Frequently Accessed Directories

alias doc="cd ~/Documents"
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias icd="cd ~/Library/Mobile\ Documents/com~apple~CloudDocs"

#### Aliases: Xcode

alias ddd="rm -rf ~/Library/Developer/Xcode/DerivedData"

#### Aliases: Miscellaneous

# Useful if AirPods aren't connecting.
alias fixaudio="sudo kill `pgrep coreaudiod`"

alias ls="ls -aGhlp"
alias scratch="code -n ~/Code/scratchpad.md"

#### Include Private .zshrc

[ -f ~/.zshrc.private ] && source ~/.zshrc.private

#### Include chruby

[[ -f /opt/dev/sh/chruby/chruby.sh ]] && type chruby >/dev/null 2>&1 || chruby () { source /opt/dev/sh/chruby/chruby.sh; chruby "$@"; }
