cask_args appdir: "/Applications"

tap "caskroom/cask"
tap "caskroom/versions"

brew "git"
brew "imagemagick"
brew "node"         # Required for Sublime-HTMLPrettify plugin
brew "rbenv"

cask "airfoil"
cask "backblaze"
cask "basictex"
cask "caskroom/versions/java8"
cask "daisydisk"
cask "dash"
cask "eclipse-ide"
cask "fantastical"
cask "fastscripts"
cask "framer"
cask "google-chrome"
cask "imageoptim"
cask "ksdiff"
cask "microsoft-office"
cask "nudgit"
cask "omnigraffle"
cask "paw"
cask "qlstephen"
cask "sequel-pro"
cask "skala-preview"
cask "sketch"
cask "skype"
cask "sublime-text"
cask "superduper"
cask "tower"
cask "transmit"
cask "vagrant"
cask "virtualbox"
cask "vlc"
